apiVersion: v1
kind: Service
metadata:
  name: {{ include "cc.fullname" . }}
  labels:
    {{- include "cc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: main
      protocol: TCP
      name: http
  selector:
    {{- include "cc.selectorLabels" . | nindent 4 }}
